version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./reference_json:/app/reference_json
    restart: always
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 